apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci-cd-app
  template:
    metadata:
      labels:
        app: ci-cd-app
    spec:
      containers:
        - name: ci-cd-container
          image: hansikagollen/ci-cd-with-docker-with-kubernetes:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-service
spec:
  type: NodePort
  selector:
    app: ci-cd-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
